### PR TITLE
Resolve jenkins windows error

### PR DESCRIPTION
**Pull request by rshiv**
This PR is to resolve https://github.com/status-im/nim-waku/issues/778 .

The key in original PR uses RSA 4096 to create key-cert pair, we changed the key-cert which is using RSA 2048, which resolves the problem of windows error.

### CODE REVIEW

**Comment by oskarth** [comment]
There still seem to be a problem with Jenkins Linux CI

https://github.com/status-im/nim-waku/pull/779#issuecomment-975036094
https://ci.status.im/blue/organizations/jenkins/nim-waku%2Fprs%2Flinux/detail/PR-777/9/pipeline

**Review by oskarth — APPROVED** [review]

**Comment by rshiv** [comment]
> There still seem to be a problem with Jenkins Linux CI. Not clear to me if this is the same or different, but would be good if we could fix that one too as it is usually the most reliable one
> 
> [#779 (comment)](https://github.com/status-im/nim-waku/pull/779#issuecomment-975036094) https://ci.status.im/blue/organizations/jenkins/nim-waku%2Fprs%2Flinux/detail/PR-777/9/pipeline

The linux issue is not related to the recent changes of websockets.

**Comment by jm-clius** [comment]
Reviving looking into the Linux failures here: https://github.com/status-im/nim-waku/issues/738

**Review by jm-clius — APPROVED** [review]
👍 Seems to fix the Windows failures.

**Pull request merged**
