### PR TITLE
Add tutorial to setup websockify

### PR DESCRIPTION
**Pull request by D4nte**

### CODE REVIEW

**Review by oskarth — APPROVED** [review]
Thanks! cc @dryajov fyi for libp2p team

**Comment by dryajov** [comment]
Hopefully, this should be short lived as we've implemented the websockets as per https://datatracker.ietf.org/doc/html/rfc6455. We'll work in integrating it with nim-libp2p next.

**Comment by oskarth** [comment]
@dryajov is it accurate that with the native implementation no domain or certificate management is necessary? even for `wss` to browsers?

**Comment by dryajov** [comment]
> @dryajov would the native implementation require any form of domain or certificate management for `wss` to browsers?

Certs are managed by chronos which uses bearssl for it's ssl implementation - bearssl embeds mozilla's certificate store from https://curl.haxx.se/ca/cacert.pem

For DNS, chronos uses `getaddrinfo` (which is blocking, so beware), which should do ipv4,6 and domain name resolution.

**Pull request merged**
