### PR TITLE
ci: add MAKE_TARGET parameter, remove default from IMAGE_TAG

### PR DESCRIPTION
**Pull request by jakubgs**
Adjustments to `Jenkinsfile` to allow building of different targets and pushing images with different tags depending on job parameters.
    
If we specify a `string` parameter in `parameters` they will be overwritten in job definition after very job build.

I created four jobs at: https://ci.status.im/job/nim-waku/

* [manual](https://ci.status.im/job/nim-waku/job/manual/) - For building by hand
* [deploy-v1-test](https://ci.status.im/job/nim-waku/job/deploy-v1-test/) - Auto build from `master`
* [deploy-v2-test](https://ci.status.im/job/nim-waku/job/deploy-v2-test/) - Auto build from `master`
* [deploy-v2-prod](https://ci.status.im/job/nim-waku/job/deploy-v2-prod/) - Triggered manually

### CODE REVIEW

**Comment by jakubgs** [comment]
Just for clarity, this:
```groovy
params.MAKE_TARGET ?: 'wakunode2'
```
Is the same thing as this ternary operator:
```groovy
params.MAKE_TARGET ? params.MAKE_TARGET : 'wakunode2'
```
But just shorter.

**Comment by jakubgs** [comment]
Why is `wakunode1` target making a `wakunode` binary:
```
Debug build; proj: /app/waku/v1/node/wakunode.nim; out: /app/build/wakunode
```
```
/app/build/wakunode1: no such file or directory
```
Do you mind if I change that to be called `wakunode1` instead of `wakunode` to be consistent?
https://github.com/status-im/nim-waku/blob/d1c93747383d3eadb01be91d192bff9fecc80a25/waku.nimble#L44-L45

**Comment by oskarth** [comment]
> deploy-v2-prod - Triggered manually

How is this done exactly? It might be good to document this. @decanus previously mentioned this might be done by tag for release, e.g. https://github.com/status-im/nim-waku/releases/tag/v0.1


> Do you mind if I change that to be called wakunode1 instead of wakunode to be consistent?

Fine by me,  we did some cleanup like that before. cc @kdeme

**Review by oskarth — APPROVED** [review]

**Review by jm-clius — APPROVED** [review]

**Comment by jakubgs** [comment]
>How is this done exactly?

It's simple, you just run the job using the `Run with parameters` button at: https://ci.status.im/job/nim-waku/job/deploy-v2-prod/

The other two jobs - `deploy-v1-test` and `deploy-v2-test` - run automatically on pushes to `master`, but `deploy-v2-prod` does not as requested in https://github.com/status-im/infra-nim-waku/issues/2:

>This will be the first cluster, we will release to this cluster whenever a new tag is pushed indicating a stable release of WakuV2.

As far as I know there is no way to automatically build on a tag. But I might be wrong.

> It might be good to document this.

Where would you like this do be documented? A separate file under `docs`? Somewhere else?

**Comment by oskarth** [comment]
@jakubgs a separate file under https://github.com/status-im/nim-waku/tree/master/docs/contributors would make sense to me!

**Comment by jakubgs** [comment]
I added a `docs/contributors/continuous-integration.md` doc.

**Comment by oskarth** [comment]
Thanks! Feel free to merge it once CI passes

**Comment by jakubgs** [comment]
I assume windows tests are not failing because of my changes which have nothing to do with that:
```
build\wakunode.exe: D:\a\_temp\735c93fb-d4d6-4ea1-989b-a2ade8dd352c.ps1:3
Line |
   3 |  build\wakunode.exe --help
     |  ~~~~~~~~~~~~~~~~~~
     | The module 'build' could not be loaded. For more information, run 'Import-Module build'.

Error: Process completed with exit code 1.
```

**Pull request merged**
