### PR TITLE
Add support for multiple protocol IDs

### PR DESCRIPTION
**Pull request by jm-clius**
This PR addresses https://github.com/status-im/nim-waku/issues/165

It adds a protocol matcher for each supported protocol (`lightpush`, `filter`, `swap`, `relay`, `store`) to support multiple protocol IDs.

Currently the matcher is very simple and will match each protocol's configured codec with a protocol ID consisting of the codec + any postfix. In other words, if the stable codec is `/vac/waku/filter/2.0.0` it will also match `/vac/waku/filter/2.0.0-beta3`, `/vac/waku/filter/2.0.0-actualnonsense`. If the current codec is `/vac/waku/filter/2.0.0-beta3`, however, it will not support `/vac/waku/filter/2.0.0-beta2`, or `/vac/waku/filter/2.0.0-beta4`.

Eventually, this matcher can be extended to something more sophisticated that supports `semver` or similar. 

This change allows us to gracefully upgrade protocol IDs in the `nim-waku` client to `stable` versions (https://github.com/vacp2p/rfc/issues/406), while still supporting clients on `alpha` or `beta` versions. cc @D4nte @richard-ramos

### CODE REVIEW

**Review by staheri14 — APPROVED** [review]
Looks Good!

**Review by oskarth — APPROVED** [review]

**Review by D4nte — APPROVED** [review]
LGTM

**Comment by D4nte** [comment]
Are you able to apply different processing logic depending on the matched string?

**Comment by jm-clius** [comment]
> Are you able to apply different processing logic depending on the matched string?

Absolutely. Not implemented as such yet, but could have a different matcher for each protocol.

**Comment by jm-clius** [comment]
@jakubgs, I think we may have a disk space issue on the Jenkins host. Windows CI job fails - first run exits with error:
```
08:50:56  C:\Users\jenkins\AppData\Local\Temp\ccvaCI3n.s: Fatal error: can't write 3888 bytes to section .debug_info of nimcache\release\wakunode2\settings.c.o: 'No space left on device'
```

**Comment by jakubgs** [comment]
Jesus christ, these builds sure take up a LOT of space:
```
admin@windows-01 MINGW64 /c/Users/jenkins/workspace
$ du -hsc ./nim-waku*
5.8G    ./nim-waku_prs_windows_PR-643
5.8G    ./nim-waku_prs_windows_PR-643@2
4.0K    ./nim-waku_prs_windows_PR-643@2@tmp
4.0K    ./nim-waku_prs_windows_PR-643@tmp
6.6G    ./nim-waku_prs_windows_PR-644
4.0K    ./nim-waku_prs_windows_PR-644@tmp
2.3G    ./nim-waku_prs_windows_PR-652
4.0K    ./nim-waku_prs_windows_PR-652@tmp
6.1G    ./nim-waku_prs_windows_PR-653
5.9G    ./nim-waku_prs_windows_PR-653@2
4.0K    ./nim-waku_prs_windows_PR-653@2@tmp
4.0K    ./nim-waku_prs_windows_PR-653@tmp
33G     total
```
Linux ones are smaller, but it's still massive:
```
jenkins@linux-01:~/workspace$ du -hsc nim-waku*
1013M	nim-waku
3.7G	nim-waku_prs_linux_PR-643
4.0K	nim-waku_prs_linux_PR-643@tmp
3.7G	nim-waku_prs_linux_PR-652
4.0K	nim-waku_prs_linux_PR-652@tmp
3.7G	nim-waku_prs_linux_PR-653
3.6G	nim-waku_prs_linux_PR-653@2
4.0K	nim-waku_prs_linux_PR-653@2@tmp
4.0K	nim-waku_prs_linux_PR-653@tmp
16G	total
```
I will have to increase the root volume, but this is quite serious. Maybe we need to run a workspace cleanup after build.

**Comment by jakubgs** [comment]
```
admin@windows-01 MINGW64 /c/Users/jenkins/workspace/nim-waku_prs_windows_PR-643 ((cdf1c74...))
$ du -hsc ./* | sort -h | tail -n4
1.4G    ./build
2.0G    ./vendor
2.1G    ./nimcache
5.6G    total
```
I assume if I calen up `nimcache` then compilation will be slower correct?
So if I'm cleaning that up I might as well purge the whole workspace.

**Comment by jm-clius** [comment]
> I will have to increase the root volume, but this is quite serious. Maybe we need to run a workspace cleanup after build.

Those are massive. 😮 Perhaps we can schedule a nightly cleanup?

**Comment by jakubgs** [comment]
Well, we could just remove the workspaces after every build, the question is how much slower would that make them. If it's just a minute or so, then we don't care.

**Comment by oskarth** [comment]
Why is it so big? How does it compare with Nimbus?

**Comment by jakubgs** [comment]
Nimbus runs `cleanWs()` to purge the workspace after build is finished:
https://github.com/status-im/nimbus-eth2/blob/44f652f704f14c67e648f2b14dee652d44b858c5/Jenkinsfile#L72-L73

So they don't take up much after the build finishes. But while the build runs it's quite big:
```
admin@linux-03.do-ams3.ci.misc:~ % sudo du -hs /home/jenkins/workspace/nimbus-eth2_multibranch_unstable
6.6G	/home/jenkins/workspace/nimbus-eth2_multibranch_unstable
```

**Comment by jm-clius** [comment]
I think we should try do the same then.

**Comment by jakubgs** [comment]
I've increased root volume size for Windows hosts in https://github.com/status-im/infra-ci/commit/faf4b193148f8192fcd1978a245e2e47d083c110, but with #655 merged this should not be an issue again.

I will also look into running the v1/v2 tests/builds depending on what changed later.

**Pull request merged**
