### PR TITLE
bump/libp2p

### PR DESCRIPTION
**Pull request by decanus**

### CODE REVIEW

**Comment by kdeme** [comment]
Merging as that CI failure seems to be an occasional failure, probably not related to this change.

**Comment by kdeme** [comment]
Hmm, might have been wrong here. Bump of libp2p might make this fail always on appveyor (windows).

**Comment by decanus** [comment]
@kdeme that to me would imply libp2p is broken on windows? cause we didn't do any real changes other than updating?

**Comment by kdeme** [comment]
I'm not sure. Might be a coincidence, or not. If it is not, yes something must have changed in libp2p that makes this fail.

But I never looked at this code so I don't know what it does or what it is supposed to do.

So I have no idea what this error is about:
```
C:\projects\nim-waku\tests\v2\test_waku.nim(51, 33): Check failed: tracker.isLeaked() == false
tracker.isLeaked() was true
false was false
C:\projects\nim-waku\tests\v2\test_waku.nim(51, 33): Check failed: tracker.isLeaked() == false
tracker.isLeaked() was true
```

**Comment by stefantalpalaru** [comment]
> would imply libp2p is broken on windows?

nim-libp2p has two Windows CI jobs - for both 32 and 64 bit systems - so it's supposed to work. Report the issue there.

**Pull request merged**
