### PR TITLE
Change page size type to uint64

### PR DESCRIPTION
**Pull request by staheri14**
Addresses https://github.com/status-im/nim-waku/issues/465

### CODE REVIEW

**Comment by staheri14** [comment]
I am getting windows error similar to this PR https://github.com/status-im/nim-waku/pull/463 guess should attack it in isolation as suggested by @oskarth  https://github.com/status-im/nim-waku/pull/463#issuecomment-815624277

**Review by D4nte — COMMENTED** [review]
LGTM

**Comment by oskarth** [comment]
@D4nte if LGTM, please approve PR to make merging easier

**Review by oskarth — APPROVED** [review]

**Comment by jm-clius** [comment]
> I am getting windows error similar to this PR #463, guess should attack it in isolation as suggested by @oskarth [#463 (comment)](https://github.com/status-im/nim-waku/pull/463#issuecomment-815624277) ?

Yeah, working on it. Will open issue for easier tracking.

**Review by jm-clius — APPROVED** [review]

**Comment by staheri14** [comment]
> > I am getting windows error similar to this PR #463, guess should attack it in isolation as suggested by @oskarth [#463 (comment)](https://github.com/status-im/nim-waku/pull/463#issuecomment-815624277) ?
> 
> Yeah, working on it. Will open issue for easier tracking.

Thanks @jm-clius!

**Pull request merged**
