### PR TITLE
feat(jsonrpc): add ENR to debug_v1_info call

### PR DESCRIPTION
**Pull request by kaiserd**
This PR solves #917.

### CODE REVIEW

**Review by oskarth — APPROVED** [review]

**Review by jm-clius — APPROVED** [review]
Thanks! It may be worth going over https://github.com/status-im/infra-role-nim-waku/blob/1e5367c86a906d9b08c0d492f5d70a85d790ae37/tasks/query.yml to double-check that the new field would not break existing scripting.

**Comment by kaiserd** [comment]
Thanks for pointing that out. I could not find any issue with the current scripting. @jakubgs wdyt?

**Comment by jakubgs** [comment]
That makes sense then. So that means the ENR is only a reference to the DevP2P port, and never to the websocket one.

**Comment by jakubgs** [comment]
Question: When I look at logs for a node I see two types of ENR records:
```
INF 2022-03-29 10:20:53.894+00:00 DNS: discoverable ENR      topics="wakunode" tid=1 file=wakunode2.nim:939 enr=enr:-Iu4QDWEWqm9mTETF3Tjnq4FxKZpuQ-JVtS10xbGLwH5lC-GDaE-leSpGb6TfXB4bQ2JxS6rpV98h3bQGEvaC4FIkLMBgmlkgnY0gmlwhEDhUe2Jc2VjcDI1NmsxoQIE3HkSvDkl2zD64j2kGMH9XZHpuu-5VYT4wnBgJApW_oN0Y3CCdl-Fd2FrdTIP
INF 2022-03-29 10:20:54.335+00:00 Discv5: discoverable ENR   topics="wakunode" tid=1 file=wakunode2.nim:903 enr=enr:-JK4QIGyJyjSlponBZqe9XZ75b5ePSU9fWw5UtxEF1vsYXTLYkTa4psnUxJPmOcJGVt9XCYpC2h2kNoowl1t5KzuW6wBgmlkgnY0gmlwhEDhUe2Jc2VjcDI1NmsxoQIE3HkSvDkl2zD64j2kGMH9XZHpuu-5VYT4wnBgJApW_oN0Y3CCdl-DdWRwgiMohXdha3UyDw
```
Why are there two? How are they different? Which one is returned from this call?

**Comment by jakubgs** [comment]
Oh, it appears the "DNS" ENR contains just the TCP multiaddress:
```
 > nimbus_beacon_node record print enr:-Iu4QDWEWqm9mTETF3Tjnq4FxKZpuQ-JVtS10xbGLwH5lC-GDaE-leSpGb6TfXB4bQ2JxS6rpV98h3bQGEvaC4FIkLMBgmlkgnY0gmlwhEDhUe2Jc2VjcDI1NmsxoQIE3HkSvDkl2zD64j2kGMH9XZHpuu-5VYT4wnBgJApW_oN0Y3CCdl-Fd2FrdTIP
(1, id: "v4", ip: 64.225.81.237, secp256k1: 0x0204DC7912BC3925DB30FAE23DA418C1FD5D91E9BAEFB95584F8C27060240A56FE, tcp: 30303, waku2: 0x0F)
```
While the DNS one also contains the UDP multiaddress:
```
 > nimbus_beacon_node record print enr:-JK4QIGyJyjSlponBZqe9XZ75b5ePSU9fWw5UtxEF1vsYXTLYkTa4psnUxJPmOcJGVt9XCYpC2h2kNoowl1t5KzuW6wBgmlkgnY0gmlwhEDhUe2Jc2VjcDI1NmsxoQIE3HkSvDkl2zD64j2kGMH9XZHpuu-5VYT4wnBgJApW_oN0Y3CCdl-DdWRwgiMohXdha3UyDw
(1, id: "v4", ip: 64.225.81.237, secp256k1: 0x0204DC7912BC3925DB30FAE23DA418C1FD5D91E9BAEFB95584F8C27060240A56FE, tcp: 30303, udp: 9000, waku2: 0x0F)
```
What's the point of having both? Is the first gonna be phased out?

**Comment by kaiserd** [comment]
> Oh, and ENR can contain multiple addresses?

Yes. An [ENR](https://eips.ethereum.org/EIPS/eip-778) may contain information that allows converting it into several multiaddresses. For example one TCP based and one UDP based multiaddress.
Further, [31/WAKU2-ENR](https://rfc.vac.dev/spec/31/) adds a multiaddr field. This Waku specific multiaddr field is used by `nim-waku` to encode a `dns4` multiaddr.

> What's the point of having both? Is the first gonna be phased out?

[nim-eth/discv5](https://github.com/status-im/nim-eth/tree/master/eth/p2p/discoveryv5), the discv5 subsystem that nim-waku uses, manages its own ENR.
We plan to consolide them in the future. #915 is a first step in that direction.

@jakubgs

**Review by jakubgs — APPROVED** [review]

**Pull request merged**
