### PR TITLE
Integrating pagination into the resume proc

### PR DESCRIPTION
**Pull request by staheri14**
Closes https://github.com/status-im/nim-waku/issues/650

### CODE REVIEW

**Comment by oskarth** [comment]
I notice Jenkins PR isn't passing for some reason? But it works for GH actions

cc @jakubgs

**Review by D4nte — APPROVED** [review]
LGTM

**Review by jm-clius — APPROVED** [review]
LGTM!

**Comment by jakubgs** [comment]
I don't know man, the errors are there:

```
[2021-06-29T21:56:43.946Z] stack trace: (most recent call last)
[2021-06-29T21:56:43.946Z] /home/jenkins/workspace/nim-waku_prs_linux_PR-653/vendor/nimbus-build-system/vendor/Nim/lib/system/nimscript.nim(416, 18)
[2021-06-29T21:56:43.946Z] /home/jenkins/workspace/nim-waku_prs_linux_PR-653/waku.nimble(75, 8) test2Task
[2021-06-29T21:56:43.946Z] /home/jenkins/workspace/nim-waku_prs_linux_PR-653/waku.nimble(42, 8) test
[2021-06-29T21:56:43.946Z] /home/jenkins/workspace/nim-waku_prs_linux_PR-653/vendor/nimbus-build-system/vendor/Nim/lib/system/nimscript.nim(260, 7) exec
[2021-06-29T21:56:43.947Z] /home/jenkins/workspace/nim-waku_prs_linux_PR-653/vendor/nimbus-build-system/vendor/Nim/lib/system/nimscript.nim(260, 7) Error: unhandled exception: FAILED: build/all_tests_v2 [OSError]
[2021-06-29T21:56:43.947Z] make: *** [Makefile:140: test2] Error 1
```
https://ci.status.im/job/nim-waku/job/prs/job/linux/job/PR-653/11/execution/node/59/log/
https://ci.status.im/job/nim-waku/job/prs/job/macos/job/PR-653/11/execution/node/59/log/

Not sure how to read those errors. There's also this:
```
23:48:17      Unhandled exception: Unable to create server! [RpcBindError]
23:48:17    [FAILED] Private API: generate symmetric keys and encrypt/decrypt communication
```

**Comment by oskarth** [comment]
Probably best to hold off on removing GH CI until we know what's going wrong and why there's a mismatch

**Comment by staheri14** [comment]
Thanks @jakubgs for posting the log of errors! 
FYI, I do not have access to the logs e.g., https://ci.status.im/job/nim-waku/job/prs/job/macos/job/PR-653/11/execution/node/59/log/, I get `Access Denied` error.

**Comment by jakubgs** [comment]
@staheri14 right, because you are yet another person that was not added to the [Status](https://github.com/orgs/status-im/teams/status) team on github.

I've added you to that team, and you should now be able to log into https://ci.status.im/. You might have to clear cookies or possibly relogin on GitHub. It is also important that you mark your membership in `status-im` GitHub organization as public.

image

It appears to be set to private right now.

**Comment by staheri14** [comment]
Thanks a lot @jakubgs! Now I have access to the logs! also made my membership in `status-im` public 👍

**Comment by staheri14** [comment]
It is weird! Cannot see why the tests have inconsistent behavior on GH actions and Jenkins

**Comment by staheri14** [comment]
@oskarth 
Just to double-confirm, shall I merge the PR?

**Comment by staheri14** [comment]
@jakubgs I have merged the master after this PR https://github.com/status-im/nim-waku/pull/655, and now Jenkins checks pass except for the windows, the error for windows is about gcc not being installed ` C compiler (gcc) not installed. Aborting.`

**Comment by jakubgs** [comment]
I'll check tomorrow. I know what it is.

**Comment by staheri14** [comment]
@jakubgs Thanks!

**Comment by jakubgs** [comment]
I gixed the GCC issue, but it looks like the v1 tests are failing the same way as before.

**Comment by jakubgs** [comment]
Ah yes, `s3cmd` was indeed missing from the host. Fixed:
```
 > a ci-slave-windows -m win_shell -a 'pypy3 C:\ProgramData\scoop\apps\pypy3\current\Scripts\s3cmd --version'
windows-02.gc-europe-west4-a.ci.misc | CHANGED | rc=0 >>
s3cmd version 2.1.0

windows-01.gc-europe-west4-a.ci.misc | CHANGED | rc=0 >>
s3cmd version 2.1.0
```

**Comment by jakubgs** [comment]
All green now.

**Comment by oskarth** [comment]
@staheri14 need rebase

**Pull request merged**
