### PR TITLE
Upgrade vendor nim-libp2p and related packages

### PR DESCRIPTION
**Pull request by oskarth**
WIP https://github.com/status-im/nim-waku/issues/12

Current:

> Error: type mismatch: got <SkResult[secp.SkPrivateKey]> but expected 'SkPrivateKey = distinct SkSecretKey'

Getting the inverse error if I add `.get()`. Probably missing something obvious

TODO: Still need to look at v1 files.

### CODE REVIEW

**Comment by kdeme** [comment]
@oskarth V1 is fine, only affected by chronos changes but that seems ok.

I had a look at the issue you were seeing and decided to immediately resolve it. I hope you don't mind :)

You were basically doing the `get` at the wrong location. That `SkPrivateKey.init` also returns a `Result` type.
Be aware by the way of the differences of `get` or `[]` and `tryGet`. The first two will return an `Defect` if they contain an error, so you should first check with `isErr` or `isOk`. (or `expect` if the result really should be fine, and you really want to crash else). 
`tryGet` on the other hand will raise the `Exception` it holds or `ResultError`, which in this case would then be catched by the `except CatchableError`.

For more info, you can read the docs here and below: https://github.com/status-im/nim-stew/blob/5fa6bb27424af823611f7c475ea1ad8635ffcaca/stew/results.nim#L450

Also, it is better to not pass the Result type as the config parameter, because then the failure when doing `get` would happen in the wakunode.nim code, and you'd have to deal with it there.
If instead you let the failure happen in the `parseCmdArg` call, then confutils will give you a somewhat nicer error message, e.g. now:
```
$ ./build/wakunode --nodekey:"skfjlksjfdlks"
Error while processing the 'nodekey' parameter:
Invalid private key
Try wakunode --help for more information.
```

**Comment by oskarth** [comment]
Thanks @kdeme! I missed that distinction and didn't go deeper. Makes sense, felt it was odd to do the Result type stuff in CLI handling already but I was mostly trying to make the errors go away :P

**Comment by oskarth** [comment]
I didn't upgrade nim-eth because it seemed out of scope and I didn't need it for v2 experimental stuff. I did notice that there seems to be some p2p protocol errors when upgrading to latest nim-eth, but I didn't investigate. Perhaps a separate fix @kdeme?

**Comment by oskarth** [comment]
Whats the difference between Appveyor and Travis CI checks? I notice 1/4 checks, and that there's a long queue in AppVeyor.

**Comment by oskarth** [comment]
39 jobs, seems kinda stuck. Going to merge as it works locally.

**Comment by kdeme** [comment]
I'll check a nim-eth bump to see if there are issues.

Appveyor & TravisCI target different architectures and OS.

**Comment by arnetheduck** [comment]
generally, it's sensible to treat the `nim-` packages as a giant monorepo and upgrade all together when doing it - we're just making our life a little extra miserable by splitting them up, when in reality split upgrades rarely will work.

**Pull request merged**
