### PR TITLE
Fixes/filter bump

### PR DESCRIPTION
**Pull request by oskarth**
https://github.com/status-im/nim-waku/issues/162

@decanus to address

### CODE REVIEW

**Comment by oskarth** [comment]
@decanus ?

**Comment by decanus** [comment]
Waiting for feedback from @dryajov on whether this is a libp2p issue or not. It’s relatively hard for me alone to grasp the libp2p architecture enough to say.

**Comment by oskarth** [comment]
I thought the previous PR already solved it? If it isn't done we can close this PR

**Comment by decanus** [comment]
@oskarth now that I look at it, it looks like it might have. But according to @dryajov some of the ways I was using the code was wrong anyway so it may make sense to merge this in.

**Comment by decanus** [comment]
moving to a new PR because this is rekt.

**Pull request closed without merging**
