### PR TITLE
Windows CI debug

### PR DESCRIPTION
**Pull request by oskarth**
Windows CI failing:

```
DBG 2021-04-25 12:37:08.925+00:00 start                                      topics="wakurelay" tid=6604
INF 2021-04-25 12:37:08.925+00:00 relay mounted and started successfully     topics="wakunode" tid=6604
DBG 2021-04-25 12:37:08.930+00:00 Waku peer initialized                      topics="waku" tid=6604 peer=Node[127.0.0.1:30303]
INF 2021-04-25 12:37:08.930+00:00 connectToNodes                             topics="wakunode" tid=6604 peer="(peerId: \"16Uiu2HAmP2esoz2xztqVLdw9wFY1aVxLbPgG8tpYAvAevJBJCpn3\", addrs: @[\"/ip4/0.0.0.0/tcp/60000\"], protocols: @[], protoVersion: \"\", agentVersion: \"\")"
DBG 2021-04-25 12:37:08.930+00:00 Adding peer to manager                     topics="wakupeers" tid=6604 peerId=16U*BJCpn3 addr=/ip4/0.0.0.0/tcp/60000 proto=/vac/waku/relay/2.0.0-beta2
INF 2021-04-25 12:37:08.930+00:00 Dialing peer from manager                  topics="wakupeers" tid=6604 wireAddr=/ip4/0.0.0.0/tcp/60000 peerId=16U*BJCpn3
DBG 2021-04-25 12:37:08.930+00:00 Dialing peer                               topics="libp2p switch" tid=6604 peerId=16U*BJCpn3
DBG 2021-04-25 12:37:08.930+00:00 Waku peer initialized                      topics="waku" tid=6604 peer=Node[127.0.0.1:50713]
DBG 2021-04-25 12:37:08.930+00:00 Accepted an incoming connection            topics="libp2p switch" tid=6604 conn=608562745f4d0000000073a3
DBG 2021-04-25 12:37:08.930+00:00 About to accept incoming connection        topics="libp2p switch" tid=6604
DBG 2021-04-25 12:37:08.932+00:00 Noise handshake, peer infos don't match!   topics="libp2p noise" tid=6604 initiator=true dealt_peer=16U*BJCpn3:608562745f4d0000000073a2 dealt_key="secp256k1 key ((data: (data: [152, 27, 186, 54, 206, 235, 80, 175, 153, 223, 5, 162, 128, 113, 73, 18, 71, 120, 3, 231, 160, 98, 50, 118, 61, 222, 141, 64, 196, 160, 33, 154, 225, 4, 147, 44, 207, 123, 214, 77, 148, 76, 237, 35, 245, 129, 44, 236, 49, 96, 189, 169, 73, 49, 82, 135, 137, 205, 9, 60, 226, 55, 102, 147])))" received_peer=Ok(16Uiu2HAkwJkLBegFqESdzRPUhxuZ9B9SQzxm1fbJMmWMdDKdvo7Y) received_key="secp256k1 key ((data: (data: [187, 142, 152, 49, 143, 55, 157, 143, 71, 232, 86, 169, 8, 160, 109, 75, 7, 143, 154, 129, 94, 137, 104, 238, 46, 140, 89, 110, 128, 58, 241, 27, 70, 34, 191, 32, 191, 52, 74, 42, 163, 165, 241, 222, 192, 161, 146, 179, 89, 13, 38, 133, 46, 159, 233, 208, 247, 71, 235, 237, 129, 179, 159, 205])))"
DBG 2021-04-25 12:37:08.933+00:00 Upgrade failed                             topics="libp2p switch" tid=6604 msg="Noise handshake, peer infos don't match! Ok(16Uiu2HAkwJkLBegFqESdzRPUhxuZ9B9SQzxm1fbJMmWMdDKdvo7Y) != 16Uiu2HAmP2esoz2xztqVLdw9wFY1aVxLbPgG8tpYAvAevJBJCpn3" peerId=16U*BJCpn3
DBG 2021-04-25 12:37:08.933+00:00 Error dialing                              topics="libp2p switch" tid=6604 conn=Connection(nil) msg="Noise handshake, peer infos don't match! Ok(16Uiu2HAkwJkLBegFqESdzRPUhxuZ9B9SQzxm1fbJMmWMdDKdvo7Y) != 16Uiu2HAmP2esoz2xztqVLdw9wFY1aVxLbPgG8tpYAvAevJBJCpn3"
DBG 2021-04-25 12:37:08.933+00:00 Dialing remote peer failed                 topics="wakupeers" tid=6604 msg="Noise handshake, peer infos don't match! Ok(16Uiu2HAkwJkLBegFqESdzRPUhxuZ9B9SQzxm1fbJMmWMdDKdvo7Y) != 16Uiu2HAmP2esoz2xztqVLdw9wFY1aVxLbPgG8tpYAvAevJBJCpn3"
INF 2021-04-25 12:37:13.934+00:00 subscribe                                  topics="wakunode" tid=6604 topic=/waku/2/default-bridge/proto
DBG 2021-04-25 12:37:13.934+00:00 Registering handler                        topics="wakunode" tid=6604 topic=/waku/2/default-bridge/proto
DBG 2021-04-25 12:37:13.934+00:00 subscribe                                  topics="wakurelay" tid=6604 pubSubTopic=/waku/2/default-bridge/proto
DBG 2021-04-25 12:37:15.935+00:00 publish                                    topics="wakunode" tid=6604 topic=/waku/2/default-bridge/proto contentTopic=0001
DBG 2021-04-25 12:37:15.936+00:00 publish                                    topics="wakurelay" tid=6604 pubSubTopic=/waku/2/default-bridge/proto message="@[10, 13, 104, 101, 108, 108, 111, 32, 102, 114, 111, 109, 32, 86, 50, 18, 4, 48, 48, 48, 49, 24, 0, 33, 0, 0, 0, 0, 0, 0, 0, 0, 170, 1, 0]"
NOT 2021-04-25 12:37:15.936+00:00 No peers for topic, skipping publish       topics="libp2p gossipsub" tid=6604 peersOnTopic=0 connectedPeers=0 topic=/waku/2/default-bridge/proto
    D:\a\nim-waku\nim-waku\tests\v2\test_waku_bridge.nim(82, 49): Check failed: v1Node.protocolState(Waku).queue.items.len == 1
    v1Node.protocolState(Waku).queue.items.len was 0
D:/a/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/unittest.nim(460) main
D:/a/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/unittest.nim(450) NimMain
D:/a/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/unittest.nim(441) PreMain
D:/a/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/unittest.nim(244) PreMainInner
D:/a/nim-waku/nim-waku/vendor/nim-unittest2/unittest2.nim(704) suitePayload
D:/a/nim-waku/nim-waku/vendor/nim-testutils/testutils/unittests.nim(16) runTestX60gensym214920001
D:/a/nim-waku/nim-waku/vendor/nim-chronos/chronos/asyncfutures2.nim(485) read
D:/a/nim-waku/nim-waku/vendor/nim-chronos/chronos/asyncfutures2.nim(472) internalCheckComplete

    Unhandled exception: index out of bounds, the container is empty [ValueError]
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
  [FAILED] Messages are bridged between Waku v1 and Waku v2
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.

libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
[Suite] Peer Storage
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
  [OK] Store, replace and retrieve from persistent peer storage
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
stack trace: (most recent call last)
D:\a\nim-waku\nim-waku\vendor\nimbus-build-system\vendor\Nim\lib\system\nimscript.nim(416, 18)
D:\a\nim-waku\nim-waku\waku.nims(72, 8) test2Task
D:\a\nim-waku\nim-waku\waku.nims(43, 8) test
D:\a\nim-waku\nim-waku\vendor\nimbus-build-system\vendor\Nim\lib\system\nimscript.nim(260, 7) exec
D:\a\nim-waku\nim-waku\vendor\nimbus-build-system\vendor\Nim\lib\system\nimscript.nim(260, 7) Error: unhandled exception: FAILED: build/all_tests_v2 [OSError]
mingw32-make: *** [Makefile:125: test2] Error 1
Error: Process completed with exit code 1.
```

Is this the same error you saw before @jm-clius?

(I suggest we deprioritize fixing Windows CI until we have addressed some other issues)

### CODE REVIEW

**Comment by oskarth** [comment]
I'm confused by why lightpush test triggers this seemingly unrelated Windows CI error. @jm-clius let me know if you have any ideas looking at CI results above.

Merging this so we don't need to worry about CI failing. Thanks @staheri14 for spotting! In future, feel free to revert bad commits, i.e. if you found out commenting out test means error goes away just go ahead and revert it without any discussion. Working master is more important.

**Comment by jm-clius** [comment]
As far as I can tell, the earlier `lightpush` test failed without cleaning up the resources it created. Specifically, it started, but never stopped, a node with external IP and port  `0.0.0.0:6000`. 
The `bridge` test tried to connect to its own peer at that address, but failed in the negotiation phase as `peerId` clashed with the still-running peer from the `lightpush` test.

```
INF 2021-04-25 12:37:08.930+00:00 connectToNodes                             topics="wakunode" tid=6604 peer="(peerId: \"16Uiu2HAmP2esoz2xztqVLdw9wFY1aVxLbPgG8tpYAvAevJBJCpn3\", addrs: @[\"/ip4/0.0.0.0/tcp/60000\"],
DBG 2021-04-25 12:37:08.932+00:00 Noise handshake, peer infos don't match!   topics="libp2p noise" tid=6604 initiator=true dealt_peer=16U*BJCpn3:608562745f4d0000000073a2 dealt_key="secp256k1 key ((data: (data: [152, 27, 186, 54, 206, 235, 80, 175, 153, 223, 5, 162, 128, 113, 73, 18, 71, 120, 3, 231, 160, 98, 50, 118, 61, 222, 141, 64, 196, 160, 33, 154, 225, 4, 147, 44, 207, 123, 214, 77, 148, 76, 237, 35, 245, 129, 44, 236, 49, 96, 189, 169, 73, 49, 82, 135, 137, 205, 9, 60, 226, 55, 102, 147])))" received_peer=Ok(16Uiu2HAkwJkLBegFqESdzRPUhxuZ9B9SQzxm1fbJMmWMdDKdvo7Y) received_key="secp256k1 key ((data: (data: [187, 142, 152, 49, 143, 55, 157, 143, 71, 232, 86, 169, 8, 160, 109, 75, 7, 143, 154, 129, 94, 137, 104, 238, 46, 140, 89, 110, 128, 58, 241, 27, 70, 34, 191, 32, 191, 52, 74, 42, 163, 165, 241, 222, 192, 161, 146, 179, 89, 13, 38, 133, 46, 159, 233, 208, 247, 71, 235, 237, 129, 179, 159, 205])))"
```

**Comment by oskarth** [comment]
Hm, interesting, since as far as I can tell all three nodes have `await node.stop()`

**Comment by jm-clius** [comment]
True, but since the `lightpush` test [failed on an unhandled exception](https://github.com/status-im/nim-waku/pull/506/checks#step:7:1332) the test execution was aborted before the nodes were stopped, and processing moved on to the next test in the suite.

**Pull request merged**
