### PR TITLE
Change contentTopic to string

### PR DESCRIPTION
**Pull request by jm-clius**
This PR addresses #447 

It changes the `WakuMessage` `contentTopic` back to `string`. Spec changes done in https://github.com/vacp2p/rfc/pull/337

#### Implementation notes:
 - The "default" content topic is now `"waku/2/default-content/proto"`. This is a rather arbitrary choice and may change once we spec [namespacing for content topics](https://github.com/vacp2p/rfc/issues/227)
 - For now, `WakuBridge` maps v2 content topics to v1 topics by selecting the first four bytes. This will change when we introduce [namespacing](https://github.com/vacp2p/rfc/issues/227)
 - Note that changing the `contentTopic` type as argument in JSON-RPC calls affects users of the API (cc @D4nte)
 - `WakuStore` [index computation for messages](https://github.com/status-im/nim-waku/blob/master/waku/v2/protocol/waku_store/waku_store.nim#L44) would have changed somewhat, as it is now using `string.toBytes()` rather than `uint32.toBytes()` in the algorithm. @staheri14, I assume this will be OK going forward, though existing stores (e.g. `test` fleet) may be affected?

#### Next steps:
- Specify namespacing for content topics: https://github.com/vacp2p/rfc/issues/227

### CODE REVIEW

**Comment by staheri14** [comment]
> * `WakuStore` [index computation for messages](https://github.com/status-im/nim-waku/blob/master/waku/v2/protocol/waku_store/waku_store.nim#L44) would have changed somewhat, as it is now using `string.toBytes()` rather than `uint32.toBytes()` in the algorithm. @staheri14, I assume this will be OK going forward,

yes, as long as it is converted to bytes, it would be fine

**Review by staheri14 — COMMENTED** [review]
It looks fine to me but the windows checks are failed

**Comment by D4nte** [comment]
> WakuStore index computation for messages would have changed somewhat, as it is now using string.toBytes() rather than uint32.toBytes() in the algorithm. @staheri14, I assume this will be OK going forward, though existing stores (e.g. test fleet) may be affected?


Can we please clarify the encoding of string so we know what `toBytes` does?

**Review by oskarth — APPROVED** [review]

**Comment by oskarth** [comment]
I wouldn't worry about Windows CI in this PR, can attack in isolation

**Comment by staheri14** [comment]
> > WakuStore index computation for messages would have changed somewhat, as it is now using string.toBytes() rather than uint32.toBytes() in the algorithm. @staheri14, I assume this will be OK going forward, though existing stores (e.g. test fleet) may be affected?
> 
> Can we please clarify the encoding of string so we know what `toBytes` does?

@D4nte we use the toBytes proc as defined in https://github.com/status-im/nim-stew/blob/ee78822e057ac5f39804ecb6ac1096734be13ef8/stew/byteutils.nim#L142

**Comment by D4nte** [comment]
> @D4nte we use the toBytes proc as defined in [status-im/nim-stew@`ee78822`/stew/byteutils.nim#L142](https://github.com/status-im/nim-stew/blob/ee78822e057ac5f39804ecb6ac1096734be13ef8/stew/byteutils.nim#L142)

Unfortunately this does not help me understand what encoding is used for nim strings. It's ok, I do not need this information anymore as topics are now string so the conversion string to bytes is not used anymore.

**Comment by oskarth** [comment]
@D4nte Did you ask in Nimbus discord as suggested for more details on encoding?

**Comment by D4nte** [comment]
> @D4nte Did you ask in Nimbus discord as suggested for more details on encoding?

So in short, there is no encoding, meaning the encoding is set by the input (e.g. terminal, browser, etc).

**Pull request merged**
