### PR TITLE
Protobuf methods for pagination

### PR DESCRIPTION
**Pull request by staheri14**
This PR addresses the following issue https://github.com/status-im/nim-waku/issues/236 and contains one single signed commit that embodies the same set of changes as in https://github.com/status-im/nim-waku/pull/237. 

I wanted to sign my comments in https://github.com/status-im/nim-waku/pull/237 , but I think I executed a wrong command due to which I couldn't rebase that branch to master. I closed this PR https://github.com/status-im/nim-waku/pull/237  and opened the new PR, with all my changes in one signed commit. Sorry for any inconvenience.

### CODE REVIEW

**Comment by oskarth** [comment]
> I wanted to sign my comments in #237 , but I think I executed a wrong command due to which I couldn't rebase that branch to master

Out of curiosity, what did you do and what happened? Perhaps there was/is easy fix for future

**Review by oskarth — APPROVED** [review]

**Comment by staheri14** [comment]
Here is the command:
git filter-branch --commit-filter 'git commit-tree -S "$@";' -- --all

My point was to sign all of my past commits

**Comment by oskarth** [comment]
Oh hm, yeah I'd probably squash and rebase, then do commit amend with -S and force push

**Comment by staheri14** [comment]
Indeed, I tried squash first, but it did not work since I had merges from the master branch.

**Pull request merged**
