### PR TITLE
Fixes the order of fields of History Response protobuf

### PR DESCRIPTION
**Pull request by staheri14**
This is to fix the mismatch between the implementation and the store specs regarding the order of fields of History Response protobuf. 

The store specs indicate that the first field of `HistoryResponse` is reserved for future use (as an identifier to match up queries with their corresponding requests). However, the nim-waku implementation does not comply with this specification.

### CODE REVIEW

**Review by oskarth — APPROVED** [review]
Thanks!

Worth adding to changelog too

**Review by jm-clius — COMMENTED** [review]
Thanks! LGTM, except that I think this is a breaking change? How is this currently implemented in the other clients?

**Comment by staheri14** [comment]
> Thanks! LGTM, except that I think this is a breaking change? How is this currently implemented in the other clients?

Not exactly a breaking change, because the specs were correct, it was only an issue on the nim-waku side which was not aligned with the specs.  If other clients are based on the specs, they won't have to undertake any updates, as the specs were correct. However, I am not sure how the interaction with the nim-waku was working previously!

**Comment by jm-clius** [comment]
> However, I am not sure how the interaction with the nim-waku was working previously!

Yeah, this is what worries me - if the other clients were working, they might have implemented it (probably did) based on the `nim-waku` implementation and not the spec.
In this case it would be "breaking" inasmuch as other clients won't work with store protocol anymore. May need to coordinate the change with them, then. Let's discuss in PM. :)

**Comment by staheri14** [comment]
> > However, I am not sure how the interaction with the nim-waku was working previously!
> 
> Yeah, this is what worries me - if the other clients were working, they might have implemented it (probably did) based on the `nim-waku` implementation and not the spec.
> In this case it would be "breaking" inasmuch as other clients won't work with store protocol anymore. May need to coordinate the change with them, then. Let's discuss in PM. :)

Right, I think that their implementation matches nim-waku not the specs, Lets discuss it in the call

**Comment by staheri14** [comment]
> Thanks!
> 
> Worth adding to changelog too

Changelog has been updated!

**Comment by staheri14** [comment]
> Thanks! LGTM, except that I think this is a breaking change? How is this currently implemented in the other clients?

Checked with @D4nte  and @richard-ramos, the go and js versions are also based on the nim implementation, not the specs. 
I am going to push the changes to the master and inform them to make the necessary changes.
There should be no concern with walletConnect as well, afaik they also interact with the test fleets which is based on the updated master. 
I think the only concern is re prod fleets that are not synced with the master, those are also going to have this change incorporated after v 5.0. 
@jm-clius  please let me know if there is anyone else that I should check with.

**Pull request merged**
