### PR TITLE
Bump submodules

### PR DESCRIPTION
**Pull request by oskarth**
Fixes https://github.com/status-im/nim-waku/issues/156

Status: No compile errors, some tests fail

### CODE REVIEW

**Comment by oskarth** [comment]
Need to get to some other tasks and I'm quite past timebox on this one, @kdeme would you be able to have a look?

**Comment by decanus** [comment]
@oskarth I can have a look.

**Comment by decanus** [comment]
@oskarth had a long look and messaged @dryajov, he will respond inline.

**Comment by dryajov** [comment]
Not sure what's going on there, I don't see any apparent issues off hand. One way to debug this would be to enable trace logging by passing `-d:chronicles_log_level=TRACE` when compiling.

**Comment by decanus** [comment]
@dryajov so it says the connection is closed, I tried figuring it out but I really can't wrap my head around it.

**Comment by dryajov** [comment]
OK, the reason why the test is failing is because the future in https://github.com/status-im/nim-waku/blob/master/waku/protocol/v2/waku_filter.nim#L119 isn't being awaited, this causes the connection (socket in this case) to close on handler exit.

The proper way to do this would be to await the `writeLp()` call and I suspect that most calls along that call-chain will need to be async and await their futures properly as well, otherwise you will run into all sorts of raise conditions like this one.

**Comment by oskarth** [comment]
Thanks, and that makes sense for filter tests. However, even with that disabled we have node tests failing:

```
[NimScript] exec: build/all_tests_v2

[Suite] WakuNode
    /home/oskarth/git/status-im/nim-waku/tests/v2/test_wakunode.nim(62, 10): Check failed: res == true
    res was false
    true was true
  [FAILED] Message published with content filter is retrievable
    /home/oskarth/git/status-im/nim-waku/tests/v2/test_wakunode.nim(110, 51): Check failed: (await completionFut.withTimeout(5.seconds)) == true
    true was true
  [FAILED] Content filtered publishing over network

[Suite] Waku Store
  [OK] handle query

[Suite] Waku Filter
    Unhandled exception: Stream EOF! [LPStreamEOFError]
  [FAILED] handle filter
```

**Comment by oskarth** [comment]
Current state: the local pub/sub test works now, over network fails. The filter one is disabled for now as it isn't being used for Nangang and is currently WIP. (@decanus to fix in separate PR) As for network state, I notice:

```
DBG 2020-09-15 11:42:34.447+08:00 publish                                    topics="wakurelay" tid=11927 pubSubTopic=chat message="@[10, 11, 104, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100, 18, 6, 102, 111,
 111, 98, 97, 114]"                                                                                                                                                                                                
TRC 2020-09-15 11:42:34.447+08:00 Publishing message on topic                topics="floodsub" tid=11927 data=0a0b68656c6c...666f6f626172 topic=chat
DBG 2020-09-15 11:42:34.447+08:00 No peers for topic, skipping publish       topics="floodsub" tid=11927 topic=chat
```

but earlier:

```
TRC 2020-09-15 11:07:28.154+08:00 decodeSubscription: decoding message       tid=761
TRC 2020-09-15 11:07:28.154+08:00 decodeSubscription: read subscribe         tid=761 subscribe=1
TRC 2020-09-15 11:07:28.154+08:00 decodeSubscription: read topic             tid=761 topic=chat
TRC 2020-09-15 11:07:28.154+08:00 decodeControl: decoding message            tid=761
TRC 2020-09-15 11:07:28.154+08:00 decoded msg from peer                      topics="pubsubpeer" tid=761 conn=16*Skz6wT:5f602fee2cb66d3c2be8aa78 peer=16*Skz6wT closed=false msg="(subscriptions: @[(subscribe: true
, topic: \"chat\")], messages: @[], control: (ihave: @[], iwant: @[], graft: @[], prune: @[]))"                                                                                                                    
TRC 2020-09-15 11:07:28.270+08:00 processing RPC message                     topics="pubsub" tid=761 msg="(subscriptions: @[(subscribe: true, topic: \"chat\")], messages: @[], control: (ihave: @[], iwant: @[], gr
aft: @[], prune: @[]))" peer=16*Skz6wT                                                                                                                                                                             
TRC 2020-09-15 11:07:28.270+08:00 about to subscribe to topic                topics="pubsub" tid=761 topicId=chat peer=16*Skz6wT
TRC 2020-09-15 11:07:28.270+08:00 peer subscribed to topic                   topics="gossipsub" tid=761 peer=16*Skz6wT topic=chat
```

So for some reason it thinks the peer isn't subscribed to the topic, but it is.

There appears to be some new stuff in how to call super/convert types with PubSub/GossipSub, so that might be related. Not sure.

**Comment by oskarth** [comment]
Not quite sure why it thinks peer isn't subscribed when it clearly is in log. Any ideas @kdeme or @dryajov?

**Comment by oskarth** [comment]
```
/home/oskarth/git/status-im/nim-waku/waku/node/v2/wakunode2.nim(88, 29) Error: undeclared field: 'PubSub' for type waku_types.WakuRelay [declared in /home/oskarth/git/status-im/nim-waku/waku/node/v2/waku_types.nim(48, 3)] 
```

When doing:

```
  let wakuRelay = WakuRelay.init(
    switch = switch,
    triggerSelf = true,
    sign = false,
    verifySignature = false).PubSub
  switch.mount(wakuRelay)
```

Which seems similar to how it is done in NBC and nim-libp2p GossipSub tests with GossipSub.init(...).PubSub.

**Comment by oskarth** [comment]
To the next person looking into this: feel free to revert the last commit. There only test fails. The last commit is trying to structure things similar to how NBC does it in eth2_networking.nim and GossipSub tests. It has compile errors that I'm not sure what the root cause is.

**Comment by oskarth** [comment]
@dryajov _this_ PR_ and the failing test is the problem. Not the filter protocol. That comes later.

**Comment by oskarth** [comment]
@decanus can you please fix the merge conflicts in this branch, they all relate to your changes in the two PRs.

This is unrelated to the current problem https://github.com/status-im/nim-waku/pull/157#issuecomment-692582909

**Comment by oskarth** [comment]
Update: it seems like using GossipSub works (`gossipEnabled=true`), but using FloodSub the subscribe isn't picked up for some reason. It might have something to do with this commit: https://github.com/status-im/nim-libp2p/pull/352/files and how WakuRelay is inheriting from GossipSub even if we use FloodSub.

**Review by dryajov — APPROVED** [review]

**Comment by oskarth** [comment]
Ok, seems like there's a bug in floodsub. Merging this as basics tests pass and we can do further work in other issues (floodsub, filter, better pubsub inherit structure, etc). Critical path is to fix Nangang.

**Pull request merged**
