### PR TITLE
Floodsub->gossipsub

### PR DESCRIPTION
**Pull request by oskarth**
Use gossipsub instead of floodsub for https://github.com/vacp2p/research/issues/37

image

## Previous error (requires upstream PR merge to fix)

```
DBG 2020-05-29 12:45:20+08:00 start                                      tid=9717 topic=WakuSub
INF 2020-05-29 12:45:20+08:00 PeerInfo                                   tid=9717 addrs=@[/ip4/127.0.0.1/tcp/60000] id=16Uiu2HAm7c6ViG4Qhnso7P6zWNBNHsFrfVM4HG3h23qPwEDZzVce
INF 2020-05-29 12:45:20+08:00 Listening on                               tid=9717 full=/ip4/127.0.0.1/tcp/60000/p2p/16Uiu2HAm7c6ViG4Qhnso7P6zWNBNHsFrfVM4HG3h23qPwEDZzVce
Traceback (most recent call last, using override)
/home/oskarth/git/github.com/status-im/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim(614) signalHandler
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
DBG 2020-05-29 12:45:23+08:00 UPnP: deleted port mapping                 topics="nat" tid=9717 externalPort=60000 internalPort=60000 protocol=TCP
DBG 2020-05-29 12:45:23+08:00 UPnP: deleted port mapping                 topics="nat" tid=9717 externalPort=60000 internalPort=60000 protocol=UDP
> 
```

### CODE REVIEW

**Comment by oskarth** [comment]
gdb backtrace

```
TRC 2020-05-29 13:10:51+08:00 starting node                              tid=19212 address=/ip4/127.0.0.1/tcp/60000
TRC 2020-05-29 13:10:51+08:00 started node on                            tid=19212 address=/ip4/127.0.0.1/tcp/60000 topic=TcpTransport
DBG 2020-05-29 13:10:51+08:00 start                                      tid=19212 topic=WakuSub
                                                                                                                                                  
Thread 1 "wakunode" received signal SIGSEGV, Segmentation fault.                                                                                  
acquire__2HkJUcgRps6pCb2VI47rGA_2 (ClE_0=<optimized out>)                                                                                         
    at /home/oskarth/git/github.com/status-im/nim-waku/vendor/nim-chronos/chronos/asyncsync.nim:101
101       if not(lock.locked) and lock.checkAll():                                                                                                
(gdb) bt
#0  acquire__2HkJUcgRps6pCb2VI47rGA_2 (ClE_0=<optimized out>)
    at /home/oskarth/git/github.com/status-im/nim-waku/vendor/nim-chronos/chronos/asyncsync.nim:101
#1  0x00000000004fd72a in acquire_continue__4EYwdYsXKdkegzrVWzd5Tw (udataX60gensym21285264_=udataX60gensym21285264_@entry=0x0, 
    ClE_0=ClE_0@entry=0x7ffff7b5df08) at /home/oskarth/git/github.com/status-im/nim-waku/vendor/nim-chronos/chronos/asyncmacro2.nim:36
#2  0x00000000004fe9ef in acquire__MYAgpiRUZe2D7FATZWIFDw (lock=<optimized out>)
    at /home/oskarth/git/github.com/status-im/nim-waku/vendor/nim-chronos/chronos/asyncmacro2.nim:63
#3  0x000000000062e4b0 in heartbeat__9cK3ZAZxSeXnaoEHnj7kSOw_12 (ClE_0=<optimized out>)
    at /home/oskarth/git/github.com/status-im/nim-waku/vendor/nim-libp2p/libp2p/protocols/pubsub/gossipsub.nim:186
#4  0x000000000061e64a in heartbeat_continue__eU9agU9bINcVtFkBu9b5RKWqQ (udataX60gensym110785051_=udataX60gensym110785051_@entry=0x0, 
    ClE_0=ClE_0@entry=0x7ffff7b5dec8) at /home/oskarth/git/github.com/status-im/nim-waku/vendor/nim-chronos/chronos/asyncmacro2.nim:36
#5  0x000000000061eb0b in heartbeat__fV9aNL9cDU09awu1BHkB3FwaQ_2 (g=<optimized out>)
    at /home/oskarth/git/github.com/status-im/nim-waku/vendor/nim-chronos/chronos/asyncmacro2.nim:63
#6  start__9cK3ZAZxSeXnaoEHnj7kSOw_11 (ClE_0=0x7ffff7b985c0)
    at /home/oskarth/git/github.com/status-im/nim-waku/vendor/nim-libp2p/libp2p/protocols/pubsub/gossipsub.nim:441
#7  0x000000000061ef7a in start_continue__MHuuBmWYVK9cHilyQhTxkoQ (udataX60gensym113745457_=udataX60gensym113745457_@entry=0x0, 
    ClE_0=ClE_0@entry=0x7ffff7b5de88) at /home/oskarth/git/github.com/status-im/nim-waku/vendor/nim-chronos/chronos/asyncmacro2.nim:36
#8  0x000000000062f8ef in start__fV9aNL9cDU09awu1BHkB3FwaQ (g=<optimized out>)
    at /home/oskarth/git/github.com/status-im/nim-waku/vendor/nim-chronos/chronos/asyncmacro2.nim:63
#9  0x0000000000635f5b in start__z74VL7nO1S7DpxBTWFQYmQ_8 (ClE_0=<optimized out>)
    at /home/oskarth/git/github.com/status-im/nim-waku/waku/protocol/v2/waku_protocol.nim:101
#10 0x0000000000639e1a in start_continue__a9c3cyC9ctFpXC3g69a9aTLGpw (udataX60gensym115020137_=udataX60gensym115020137_@entry=0x0, 
    ClE_0=ClE_0@entry=0x7ffff7b5de08) at /home/oskarth/git/github.com/status-im/nim-waku/vendor/nim-chronos/chronos/asyncmacro2.nim:36
#11 0x000000000063b87f in start__lTOaVrj9a3BOKN3dl4bklNA (w=<optimized out>)
    at /home/oskarth/git/github.com/status-im/nim-waku/vendor/nim-chronos/chronos/asyncmacro2.nim:63
#12 0x0000000000662db6 in start__9cfjAX8xYK6LSXH3s2RA0Vw_12 (ClE_0=<optimized out>)
    at /home/oskarth/git/github.com/status-im/nim-waku/vendor/nim-libp2p/libp2p/switch.nim:328
#13 0x000000000066675f in start_continue__11xij9aPn4UtkJalcSTxmZg (udataX60gensym122760059_=udataX60gensym122760059_@entry=0x0, 
    ClE_0=ClE_0@entry=0x7ffff7b5d808) at /home/oskarth/git/github.com/status-im/nim-waku/vendor/nim-chronos/chronos/asyncmacro2.nim:39
#14 0x000000000067207f in start__kQ8hwzs2wu2gEp5x2sQBiw (s_0=s_0@entry=0x7ffff7b90048)
    at /home/oskarth/git/github.com/status-im/nim-waku/vendor/nim-chronos/chronos/asyncmacro2.nim:63
```

**Comment by oskarth** [comment]
Ok finally figured it out. The issue is that `method initPubSub*(w: WakuSub) =` in `waku_protocol` was calling `  procCall GossipSub(w).initPubSub()`, but `GossipSub` `initPubSub` wasn't public. Instead, the `FloodSub` and/or `PubSub` `initPubSub` method was called. This meant that `  g.heartbeatLock = newAsyncLock()` was never initialized and we get the stacktrace above.

Issuing bugfix PR upstream, with that fix `wakunode` runs as normal.

**Comment by arnetheduck** [comment]
the is-a relationship here is strenuous at bast - might want to move to encapsulation

**Comment by oskarth** [comment]
> the is-a relationship here is strenuous at bast - might want to move to encapsulation

Yeah agree, haven't gotten around to it

**Pull request merged**
